### ISSUE TITLE
session 0 crashes

### ISSUE THREAD

**Issue by ghostebony** [Unpackerr/unpackerr#246]
the issue occour when is started in session 0

```
2022/12/20 16:25:06 Unpackerr v0.10.1 Starting! (PID: 31468) 2022-12-20 16:25:06.0490523 -0300 -03 m=+0.003073601
2022/12/20 16:25:06 ==> GoLift Discord: https://golift.io/discord <==
2022/12/20 16:25:06 ==> Startup Settings <==
2022/12/20 16:25:06  => Sonarr Config: 1 server: http://127.0.0.1:8989, apikey:true, timeout:1m, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["K:\\Download\\sonarr\\_automatic"]
2022/12/20 16:25:06  => Radarr Config: 1 server: http://127.0.0.1:7878, apikey:true, timeout:1m, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["G:\\Download\\radarr\\_automatic"]
2022/12/20 16:25:06  => Lidarr Config: 0 servers
2022/12/20 16:25:06  => Readarr Config: 0 servers
2022/12/20 16:25:06  => Folder Config: 0 paths, event buffer: 20000
2022/12/20 16:25:06  => Using Config File: E:\Programs\unpackerr\unpackerr.conf
2022/12/20 16:25:06  => Parallel: 1
2022/12/20 16:25:06  => RAR Passwords: 0
2022/12/20 16:25:06  => Interval: 5m
2022/12/20 16:25:06  => Start Delay: 3m
2022/12/20 16:25:06  => Retry Delay: 5m, max: 3
2022/12/20 16:25:06  => Debug / Quiet: false / false
2022/12/20 16:25:06  => Activity / Queues: false / 1m
2022/12/20 16:25:06  => Log File: E:\Programs\unpackerr\.log (10 @ 10Mb)
2022/12/20 16:25:06  => Webhook Configs: 0 URLs
2022/12/20 16:25:06  => Command Hook Configs: 0 cmds
2022/12/20 16:25:06 [Radarr] Updated (http://127.0.0.1:7878): 43 Items Queued, 43 Retrieved
2022/12/20 16:25:06 [Sonarr] Updated (http://127.0.0.1:8989): 52 Items Queued, 52 Retrieved
2022/12/20 16:26:06 [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
2022/12/20 16:26:06 [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x60 pc=0xd282d6]

goroutine 10 [running]:
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).updateTray(0xc0002ef810, 0x8fb265?, 0x18cb3fe0cc8?, 0x58?, 0x18c8ed70a28?, 0x60?, 0xc000380000?, 0xc000086120?, 0x0?, 0x0, ...)
	/home/travis/gopath/src/github.com/davidnewhall/unpackerr/pkg/unpackerr/tray.go:206 +0xb6
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).logCurrentQueue(0xc0002ef810)
	/home/travis/gopath/src/github.com/davidnewhall/unpackerr/pkg/unpackerr/logs.go:166 +0x7f4
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).Run(0xc0002ef810)
	/home/travis/gopath/src/github.com/davidnewhall/unpackerr/pkg/unpackerr/start.go:231 +0x257
created by github.com/davidnewhall/unpackerr/pkg/unpackerr.Start
	/home/travis/gopath/src/github.com/davidnewhall/unpackerr/pkg/unpackerr/start.go:154 +0x396
```

**Comment by davidnewhall** [comment]
What's a session 0? Does it support a graphical interface? ie. the system tray. If not, you need to disable the system tray by passing `USEGUI=false` as an environment variable.

More: https://github.com/davidnewhall/unpackerr/wiki/Running-unpackerr-as-a-Windows-service

**Comment by davidnewhall** [comment]
Please let me know if you got this working.

**Comment by ghostebony** [comment]
sorry for not returning, it got lost in notifications.
it was running as a service and do not have access to a GUI.
I gave up on using it as a service, with no real advantages.
It probably would have been fixed by using `USEGUI=false`.
