### ISSUE TITLE
Mismatch Directory Ownership and Run_As Context Crash

### ISSUE THREAD

**Issue by johnsondnz** [Unpackerr/unpackerr#248]
In my case an NFS share with user id 1026, and group id 100 owning the directories/files.  Without proper run_as context unpackerr cannot read/write to directories and/or files and it crashes with a panic on start.

## File Ownership
```
# ls -ln
total 0
drwxrwxrwx 1 1026 100 0 Jan  7 17:23 audiobooks
drwxrwxrwx 1 1026 100 0 Jan  7 16:32 movies
drwxrwxrwx 1 1026 100 0 Jan  5 15:12 music
drwxrwxrwx 1 1026 100 0 Jan  5 15:14 tv
```

## ENVARS
```
environment_vars:
  - { name: UN_DEBUG, value: true }
  - { name: UN_INTERVAL, value: 2m }
  - { name: UN_SONARR_0_PATHS_0, value: /data/completed/tv }
  - { name: UN_RADARR_0_PATHS_0, value: /data/completed/movies }
  - { name: UN_LIDARR_0_PATHS_0, value: /data/completed/music }
  - { name: UN_READARR_0_PATHS_0, value: /data/completed/audiobooks }
  - { name: UN_SONARR_0_URL, value: http://sonarr-http:8989 }
  - { name: UN_RADARR_0_URL, value: http://radarr-http:7878 }
  - { name: UN_LIDARR_0_URL, value: http://lidarr-http:8686 }
  - { name: UN_READARR_0_URL, value: http://readarr-http:8787 }
  -  API KEYS truncated
```

## Traceback
```
2023/01/07 17:16:08.355729 start.go:129: Unpackerr v0.10.1 Starting! (PID: 1) 2023-01-07 17:16:08.354319518 +1300 NZDT m=+0.003382626
2023/01/07 17:16:08.410458 logs.go:226: ==> GoLift Discord: https://golift.io/discord <==
2023/01/07 17:16:08.410488 logs.go:227: ==> Startup Settings <==
2023/01/07 17:16:08.410604 sonarr.go:82: => Sonarr Config: 1 server: http://sonarr-http:8989, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/data/completed/tv"]
2023/01/07 17:16:08.410631 radarr.go:82: => Radarr Config: 1 server: http://radarr-http:7878, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/data/completed/movies"]
2023/01/07 17:16:08.410645 lidarr.go:82: => Lidarr Config: 1 server: http://lidarr-http:8686, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/data/completed/music"]
2023/01/07 17:16:08.410658 readarr.go:82: => Readarr Config: 1 server: http://readarr-http:8787, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/data/completed/audiobooks"]
2023/01/07 17:16:08.410679 folder.go:74: => Folder Config: 0 paths, event buffer: 20000
2023/01/07 17:16:08.410690 logs.go:233: => Using env variables only. Config file not found.
2023/01/07 17:16:08.410698 logs.go:234: => Parallel: 1
2023/01/07 17:16:08.410705 logs.go:235: => RAR Passwords: 0
2023/01/07 17:16:08.410714 logs.go:236: => Interval: 2m
2023/01/07 17:16:08.410722 logs.go:237: => Start Delay: 1m
2023/01/07 17:16:08.410730 logs.go:238: => Retry Delay: 5m, max: 3
2023/01/07 17:16:08.410738 logs.go:239: => Debug / Quiet: true / false
2023/01/07 17:16:08.410748 logs.go:240: => Activity / Queues: false / 1m
2023/01/07 17:16:08.410762 logs.go:243: => Directory & File Modes: 755 & 644
2023/01/07 17:16:08.410770 webhook.go:228: => Webhook Configs: 0 URLs
2023/01/07 17:16:08.410780 cmdhook.go:124: => Command Hook Configs: 0 cmds
2023/01/07 17:16:08.411286 folder.go:102: [ERROR] Watching Folders: fsnotify.NewWatcher: too many open files
2023/01/07 17:16:08.418279 lidarr.go:119: [Lidarr] Updated (http://lidarr-http:8686): 0 Items Queued, 0 Retrieved
2023/01/07 17:16:08.431187 radarr.go:119: [Radarr] Updated (http://radarr-http:7878): 0 Items Queued, 0 Retrieved
2023/01/07 17:16:08.438182 readarr.go:119: [Readarr] Updated (http://readarr-http:8787): 6 Items Queued, 6 Retrieved
2023/01/07 17:16:08.504918 sonarr.go:119: [Sonarr] Updated (http://sonarr-http:8989): 0 Items Queued, 0 Retrieved

[... truncated ...]

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7f23fd]
goroutine 44 [running]:
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).Run(0xc00015b9d0)
/unpackerr/pkg/unpackerr/start.go:223 +0xbd
created by github.com/davidnewhall/unpackerr/pkg/unpackerr.Start
/unpackerr/pkg/unpackerr/start.go:154 +0x3ca 
```

Running on Kubernetes is is necessary to set security context with run as user and group to match the directory permissions, same would be for docker as you mention in the docker-compose.yml example.

Preferred failure mode would be to log an error message detailing file permission issue before controlled exit.

**Comment by davidnewhall** [comment]
A panic is definitely not a controlled exit.

Thanks for the bug report!

**Comment by davidnewhall** [comment]
The bug was triggered by this system error `too many open files`. The system error should have caused a controlled exit, and that is the bug I'm going to fix. When that error occurred a data structure failed to initialize. The app then tried to read from that uninitialized data and it crashed.

**Comment by davidnewhall** [comment]
This should work better in the new release. Please let me know.

**Comment by johnsondnz** [comment]
Closing issue, since I noticed the file permissions issue and fixed running user/group I have not hit another fatal exit.

**Comment by davidnewhall** [comment]
Glad you got it working! I hope that the changes I made based on your report will make it less likely to happen.

Appreciate you following up!
